name: visionnets
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.16
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - pip=23.0.1
  - pip:
    - scikit-learn==1.2.2
    - tqdm==4.65.0
    - wandb